# Site settings
title: A blog about lorem ipsum dolor sit amet
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Java Developer
user_description: 14年毕业至今三年之久，在此期间，参与设计开发管理的项目品类众多。囊括了传统ERP软件/互联网产品（易联众等企业软件/途牛旅游产品（H5/APP/WAP/OPENAPI）/电信APP等）。在众多的项目中本人几乎从0到1。经历风雨，逐步蜕变，到目前为止依然走在通往天听的路上，不骄不躁，脚踏实地，努力的奋斗着。当然在这期间也有一些眼高手低的时候，本以为ssh/ssm可以解读所有的javaweb项目，但是随着新事物的不断出现，发现技术的革新迭代实则很快，在追逐系统性能的路上不得不引入许多新的闻所未闻的事物。这些都需要我这个初出茅庐的眼高手低的新人不断的学习吸收与扩展。最后，引入一段话作为自勉：实澹泊而寡欲兮，独怡乐而长吟；声皦皦而弥厉兮，似贞士之戒心。要学的东西还有很多，静而不静，动而不动。
user_title: Software Developer
email: 714232542@qq.com
twitter_username: blinkingso
github_username:  blinkingso
gplus_username:  blinkingso

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
