# Site settings
title: blinkingso的个人说明
description: blinkingso的个人说明

# User settings
username: Java开发工程师
user_description: 14年毕业至今三年之久，在此期间，参与设计开发管理的项目品类众多。在众多的项目中本人几乎从0到1。经历风雨，逐步蜕变，到目前为止依然走在通往天听的路上，不骄不躁，努力的奋斗着。当然在这期间也有一些眼高手低的时候，随着新事物的不断出现，发现技术的革新迭代实则很快，在追逐系统性能的路上不得不引入许多新的闻所未闻的事物。这些都需要我这个新人不断的学习吸收。实澹泊而寡欲兮，独怡乐而长吟；声皦皦而弥厉兮，似贞士之戒心。静而不静，动而不动。
user_title: 软件开发工程师
email: 714232542@qq.com
twitter_username: blinkingso
github_username:  blinkingso
gplus_username:  blinkingso

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
